version: "3.8"

services:
  migrations:
    image: mediacms/mediacms:7.3
    command: ["/bin/bash", "/home/mediacms.io/mediacms/scripts/run-migrations.sh"]
    environment:
      ADMIN_USER: 'admin'
      ADMIN_EMAIL: 'admin@localhost'
      ADMIN_PASSWORD: # ADMIN_PASSWORD: 'uncomment_and_set_password_here'
    restart: "no"
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
    volumes:
      - ./custom:/home/mediacms.io/mediacms/custom:ro
      - static_files:/home/mediacms.io/mediacms/static
      - media_files:/home/mediacms.io/mediacms/media_files
      - logs:/home/mediacms.io/mediacms/logs

  web:
    image: mediacms/mediacms:7.3
    restart: unless-stopped
    expose:
      - "9000"
    depends_on:
      migrations:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
    volumes:
      - ./custom:/home/mediacms.io/mediacms/custom:ro
      - static_files:/home/mediacms.io/mediacms/static
      - media_files:/home/mediacms.io/mediacms/media_files
      - logs:/home/mediacms.io/mediacms/logs

  nginx:
    image: mediacms/mediacms-nginx:7.3
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - web
    volumes:
      - ./custom/static:/var/www/custom:ro
      - static_files:/var/www/static:ro
      - media_files:/var/www/media:ro
      - logs:/var/log/mediacms

  celery_beat:
    image: mediacms/mediacms-worker:7.3
    restart: unless-stopped
    command: ["/home/mediacms.io/bin/celery", "-A", "cms", "beat", "--loglevel=INFO", "--schedule=/home/mediacms.io/mediacms/logs/celerybeat-schedule"]
    depends_on:
      migrations:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
    volumes:
      - ./custom:/home/mediacms.io/mediacms/custom:ro
      - media_files:/home/mediacms.io/mediacms/media_files
      - logs:/home/mediacms.io/mediacms/logs

  celery_short:
    image: mediacms/mediacms-worker:7.3
    restart: unless-stopped
    command: ["/home/mediacms.io/bin/celery", "-A", "cms", "worker", "-Q", "short_tasks", "-c", "10", "--soft-time-limit=300", "--loglevel=INFO", "-n", "short@%h"]
    depends_on:
      migrations:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
    volumes:
      - ./custom:/home/mediacms.io/mediacms/custom:ro
      - media_files:/home/mediacms.io/mediacms/media_files
      - logs:/home/mediacms.io/mediacms/logs

  celery_long:
    image: mediacms/mediacms-worker:7.3
    # To use extra codecs, change image to: mediacms/mediacms-worker:7.3-full
    restart: unless-stopped
    command: ["/home/mediacms.io/bin/celery", "-A", "cms", "worker", "-Q", "long_tasks", "-c", "1", "-Ofair", "--prefetch-multiplier=1", "--loglevel=INFO", "-n", "long@%h"]
    depends_on:
      migrations:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
    volumes:
      - ./custom:/home/mediacms.io/mediacms/custom:ro
      - media_files:/home/mediacms.io/mediacms/media_files
      - logs:/home/mediacms.io/mediacms/logs

  db:
    image: postgres:17.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: mediacms
      POSTGRES_PASSWORD: mediacms
      POSTGRES_DB: mediacms
      TZ: Europe/London
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  postgres_data:
  static_files:
  media_files:
  logs:
